version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres-db
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgres
  user-service:
    depends_on:
      - postgresdb
    build: ./user-service
    restart: on-failure
    ports:
      - "8084:8084"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgresdb:5432/postgres-db",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "123456",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.flyway.baseline-on-migrate" : "true"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  room-service:
    depends_on:
      - postgresdb
    build: ./room-service
    restart: on-failure
    ports:
      - "8083:8083"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgresdb:5432/postgres-db",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "123456",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.flyway.baseline-on-migrate" : "true"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
